# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e475f4e2aea2e327001b88abbc08258f9535cf830086b0a043ab050350f86270478757a52dbcef5c7cbf2a0c5c84d75aecb728c328397c8b57ed6858040612c1

test:
  secret_key_base: e3383b319b736d497985eb6a3c120742ef7257726dba47d9f211063a7eedda2ba136cbf4309c900450da78b0eb81be2b061760a6bae6f28b2dc9beddec7e27e7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
